### ISSUE TITLE
No member named 'xy' in 'glm::tvec3<float, glm::precision::packed_highp>'

### ISSUE THREAD

**Issue by pierrextardif** [prisonerjohn/ofxWarp#3]
Hi, 

I'm trying to compile the example and I'm getting this:

```No member named 'xy' in 'glm::tvec3<float, glm::precision::packed_highp>'```

(on WarpBilinear.cpp line 494), and a couple of other places.

I'm on Mac using xCode 9.3, using OF 10.0, from the download page of OF.

<img width="1033" alt="screen shot 2018-05-22 at 11 59 26" src="https://user-images.githubusercontent.com/6206595/40358584-9d1ce98a-5db7-11e8-8ea8-6525947228c0.png">

It does work with the candidate number 4 of OF 10.0 (from [here](https://forum.openframeworks.cc/t/0-10-0-release-candidate-4/29423)).

How would you solve this?

**Comment by prisonerjohn** [comment]
Hi Pierre,

Indeed all the swizzle methods aren't included by default with the latest
OF.

I'm not sure when I'll have time to fix this, but in the meantime, anywhere
you see something along the lines of:
    someVec.xy
You can replace with:
    glm::vec2(someVec)

Hope this helps!

**Comment by pierrextardif** [comment]
Yes it does.

Well I guess I'll stick to the candidate as the use of the addon is for researches.
(amazing work btw).

**Comment by prisonerjohn** [comment]
Fixed in 850125c08ce70837481f5719057d9dd9c6c6680e
